### ISSUE TITLE
Add a form check list with `blue` and `red` on it

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/OpenCV-Masker-Django#19]
# Add a form check list with `blue` and `red` on it

Add a form check list with `blue` and `red` on it

### Files

- `homepage.html`

### Tasks

- [ ] Research how to dropdown list to a django form
- [ ] Add `RED` and `BLUE` to it
- [ ] Run and refactor

**Has the feature been requested before?**

No

**If the feature request is approved, would there be a need for further development in this area?**
Yes, further color options should be added.
