### ISSUE TITLE
Refactor `views.video` to call `Masker.apply_mask` with color in form

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/OpenCV-Masker-Django#20]
# Refactor `views.video` to call `Masker.apply_mask` with color in form

**Is your feature request related to a problem? Please describe.**
Refactor `views.video` to call `Masker.apply_mask` with color value sent in form from a dropdown checklist.

### Files

- `views.py`

### Tasks

- [ ] - Research how to get the color value from the form
- [ ] Get the color value from the form
- [ ] Turn it into a list and pass it to `Masker.apply_mask`
- [ ] Run and refactor

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**

No.
